
name: tests
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  test-configs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: brokeyourbike/ocvalidate-action@v0.3
        with:
          opencore-version: '0.9.3'
          release: true

      - run: |
          ocvalidate "OC/config.plist" || exit 1
